backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "src/assets/img" # Media files will be stored in the repo under images/uploads

collections:
  #Global Settings
  - name: "global-settings"
    label: "Global Settings"
    slug: "{{slug}}"
    files:

      # Site Metadata
      - label: "Metadata"
        name: "metadata"
        file: "src/_data/metadata.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }

      # Global Settings
      - label: "Global Settings"
        name: "global"
        file: "src/_data/global.json"
        fields:
          - { label: "Enable Theme switch", name: "enable_theme_switch", widget: "boolean", required: true }
          - { label: "Switch Theme Icon (.svg)", name: "switch_theme_icon", widget: "image", required: true }
          - { label: "Use System Theme", name: "use_system_theme", widget: "boolean", required: true }
          - {
              label: "Default Theme",
              name: "default_theme",
              widget: "select",
              options: ["light", "dark"],
              default: "light",
              required: true
            }
          - { label: "Logo (.svg)", name: "logo", widget: "image", required: true }
          - { label: "Mobile Menu Icon (.svg)", name: "menu_icon", widget: "image", required: true }
          - { label: "Close Icon (.svg)", name: "close_icon", widget: "image", required: true }

  # Articles
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "text" }
      - {
          label: "Meta Description",
          name: "metaDescription",
          widget: "text",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

  # Projects
  - name: "project"
    label: "Project"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Emoji", name: "emoji", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "text" }
      - {
          label: "Meta Description",
          name: "metaDescription",
          widget: "text",
          required: false,
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

  # Pages
  - name: "pages"
    label: "Page"
    slug: "{{slug}}"
    files:

      # Home page
      - label: "Home Page"
        name: "home"
        file: "src/_data/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - { label: Image, name: image, widget: image, required: false }
          - {
              label: Image Alt Text,
              name: image_alt,
              widget: string,
              required: false,
            }

      # About page
      - label: "About Page"
        name: "about"
        file: "src/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              required: false,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }

      # Blog Page
      - label: "Blog Page"
        name: "blog"
        file: "src/pages/blog.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              required: false,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }

      # Projects Page
      - label: "Projects Page"
        name: "projects"
        file: "src/pages/projects.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              required: false,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }

      # Contact Page
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown", required: false }
          - {
              label: "Meta Description",
              name: "metaDescription",
              widget: "text",
              required: false,
            }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
            name: "eleventyNavigation"
            widget: "object"
            fields:
              - { label: "Key", name: "key", widget: "string" }
              - { label: "Order", name: "order", widget: "number", default: 0 }
